# Generated by Django 3.1.6 on 2021-08-09 09:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210809_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 9, 9, 26, 26, 232909, tzinfo=utc)),
        ),
    ]
